words:
  - aabb
  - aallll
  - achi
  - afat
  - affs
  - afsplitter
  - amberg
  - amscd
  - andro
  - androideabi
  - antbhj
  - apsp
  - arbitary
  - armeabi
  - armv
  - arxiv
  - auratus
  - bandizip
  - berlios
  - besl
  - bigg
  - bili
  - bilibili
  - blanz
  - blinear
  - bmatrix
  - bmqty
  - bochs
  - bootx
  - braket
  - bssro
  - btrfs
  - calcuated
  - callq
  - cangshui
  - carassius
  - cbfs
  - cbls
  - cbmemc
  - cbtime
  - ccaba
  - cdept
  - cdev
  - cfdisk
  - charp
  - chech
  - civita
  - clangd
  - codel
  - cogdl
  - compliation
  - cpuid
  - csapp
  - cscco
  - csim
  - ctarget
  - danmaku
  - dfacs
  - dfly
  - dpad
  - efifwsetup
  - ehci
  - eigendecomposition
  - empheq
  - eqnarray
  - eqref
  - ethz
  - executue
  - exfctest
  - extpfeil
  - facs
  - fdisk
  - filp
  - flensburg
  - frobenius
  - fshelp
  - ftdi
  - gcry
  - geli
  - geman
  - gensymb
  - gflop
  - gfxmenu
  - gfxterm
  - glfw
  - gmem
  - gomod
  - gouraud
  - grubenv
  - gruber
  - grubx
  - gzio
  - hankel
  - hardirq
  - hdparm
  - hitokoto
  - hwcache
  - hwmonitor
  - ichim
  - icra
  - ientity
  - ijkmedia
  - ijkplayer
  - ioremap
  - iounmap
  - irecv
  - irqrestore
  - irst
  - isend
  - isoc
  - iucode
  - iwctl
  - jfield
  - jfloat
  - jmethod
  - jmpq
  - jscoverage
  - kanade
  - kfree
  - kiocb
  - kmalloc
  - kops
  - kunzhou
  - lefort
  - libgomp
  - libijksdl
  - liblaf
  - liblafme
  - libtirpc
  - liinwww
  - liqin
  - llseek
  - loadu
  - loff
  - lsefi
  - lsefimmap
  - lsefisystab
  - lsmmap
  - lssal
  - luks
  - lzopio
  - mathbb
  - mathfrak
  - mathjax
  - mcts
  - mdelay
  - mdet
  - mdraid
  - memrw
  - mhchem
  - miniconda
  - mkconfig
  - mmcli
  - nayak
  - newc
  - nilfs
  - nivedita
  - noarch
  - noerrors
  - nofs
  - noqueue
  - noretry
  - nuxt
  - nvme
  - nvprof
  - offsetio
  - ohci
  - openmp
  - parameterizes
  - percona
  - phace
  - phong
  - plast
  - pmatrix
  - pmqty
  - ppca
  - prebuilts
  - preds
  - printk
  - pyhd
  - pyparsing
  - pyqt
  - qdisc
  - qqtext
  - rcases
  - rdmsr
  - rdtscl
  - rdtscll
  - reiserfs
  - relocator
  - repz
  - retq
  - rface
  - rgbd
  - rijndael
  - rmmod
  - romfs
  - rskull
  - rtarget
  - rwsem
  - sbat
  - sbctl
  - sbmqty
  - sbsign
  - sbsigntools
  - sbverify
  - schedulable
  - schwarz
  - screwllum
  - sdept
  - shimx
  - shittity
  - shperical
  - slience
  - smdet
  - smem
  - smqty
  - spkmodem
  - spmqty
  - sspstrong
  - stepi
  - stirde
  - storeu
  - succesfully
  - sunpc
  - svmqty
  - sysfs
  - taehyun
  - tgcalls
  - tgwl
  - thacker
  - tikhonov
  - tmenuentry
  - tmpxft
  - tname
  - tomasi
  - typst
  - udelay
  - uhci
  - umbc
  - undeformed
  - unpose
  - unposing
  - unrar
  - upenn
  - upgreek
  - usbms
  - venti
  - vfat
  - viseme
  - vmalloc
  - vmatrix
  - voxel
  - vuepress
  - wikikg
  - worsch
  - wrmsr
  - wunused
  - xxxyyyzzz
  - xzio
  - yoimiya
  - zotero
ignorePaths:
  - "*-lock.*"
  - "*.lock"
dictionaries:
  - bash
  - cpp
  - cpp-legacy
  - cpp-refined
  - data-science
  - dotnet
  - en-gb
  - fullstack
  - golang
  - java
  - latex
  - makefile
  - node
  - npm
  - python
  - swift
  - typescript
allowCompoundWords: true
