on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true
      - uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: pnpm
      - run: make build
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/.vuepress/dist
          single-commit: true
